# ===================================================================
# Global Dev Configuration (Shared by all microservices in DEV)
# ===================================================================

# Zipkin Endpoint for DEV (Docker environment)
management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.tracing.export.zipkin.endpoint=http://zipkin:9411/api/v2/spans

# Logging levels in DEV
logging.level.org.springframework.web=INFO
logging.level.org.springframework.cloud.gateway=DEBUG
