# Dev properties for smart-mobility-gateway-01 (served by config server)
# Overrides for development environment

spring.profiles.active=dev
spring.application.name=smart-mobility-gateway-01
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://keycloak:8080/realms/smart-mobility

# Gateway discovery locator
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Logging
logging.level.root=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG

# Server
server.port=8765
server.address=0.0.0.0

# Eureka (use local dev Eureka)
eureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.preferIpAddress=true

eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
